@extends('user.layout')
	@section('body')
	<div class="container-fluid bg-grey">
	    	<div class="container">
	            <div class="row">
	                <div class="col-lg-12">                
	                    <ol class="breadcrumb">
	                      <li><a href="{{URL::route('user.home')}}">Home</a></li>
	                      <li><a href="{{URL::route('user.store.privacy')}}">Privacy Policy</a></li>
	                    </ol>     
	                </div>                                
	            </div>
	        </div>
	  </div>
	
	  	 <div class="row marginDefaultSet">
    		<img src="/assets/assest_view/images/banner-services.jpg" class="img-responsive" style="width:100%">
    	</div>
    	<div class="bottom-40"></div>
    	<div class="container page-title">
    		<div class="no-border">privacy policy</div>
    	</div>
    	<div class="container">
    		<div class="col-md-9">
    			<div class="col-lg-12">  
    				<h3 class="underline">Privacy Policy</h3> 
    				<div class="bottom-40"></div>
    				<h3>Internet Privacy and Cookies Policy</h3>
    				<p>At Compare Jersey we are committed to safeguarding and preserving the privacy of our visitors and users. This Privacy Policy document (the "Policy") has been provided by the legal resource DIY Legals and reviewed and approved by their solicitors.</p>
    				<p>This Policy explains what happens to any personal data that you provide to us, or that we collect from you whilst you visit our site and how we use cookies on this website.</p>
    				<p>We do update this Policy from time to time so please do review this Policy regularly.</p>
    				<div class="bottom-40"></div>
    				<h3>Information That We Collect</h3>
    				<p>In running and maintaining our website we may collect and process the following data about you:</p>
    				<p>* Information about your use of our site including details of your visits such as pages viewed and the resources that you access. Such information includes traffic data, location data and other communication data.</p>
    				<p>* Information provided voluntarily by you. For example, when you register for information or make a purchase.</p>
    				<p>* Information that you provide when you communicate with us by any means.</p>
    				<div class="bottom-40"></div>
    				<h3>Use of Cookies</h3>
    				<p>Cookies provide information regarding the computer used by a visitor. We may use cookies where appropriate to gather information about your computer in order to assist us in improving our website.</p>
    				<p>We may gather information about your general internet use by using the cookie. Where used, these cookies are downloaded to your computer and stored on the computer's hard drive. Such information will not identify you personally; it is statistical data which does not identify any personal details whatsoever.</p>
    				<p>Our Registered Companies may also use cookies, over which Compare Jersey has no control. Such cookies (if used) would be downloaded once you click on advertisements links on our website and are directed to third party websites.</p>
    				<p>You can adjust the settings on your computer to decline any cookies if you wish. This can be done within the "settings" section of your computer. For more information please read the advice at AboutCookies.org.</p>
    				<div class="bottom-40"></div>
    				<h3>Use of Your Information</h3>
    				<p>We use the information that we collect from you to provide our services to you. In addition to this we may use the information for one or more of the following purposes:</p>
    				<p>* To provide information to you that you request from us relating to our products or services.</p>
    				<p>* To provide information to you relating to other products that may be of interest to you. Such additional information will only be provided where you have consented to receive such information.</p>
    				<p>* To inform you of any changes to our website, services or goods and products.</p>
    				<p>If you have previously purchased goods or services from us we may provide to you details of similar goods or services, or other goods and services, that you may be interested in.</p>
    				
    				<div class="bottom-40"></div>
    				<h3>Disclosing Your Information</h3>
    				<p>We will not disclose your personal information to any other party other than in accordance with this Privacy Policy and in the circumstances detailed below:</p>
    				<p>* In the event that we sell any or all of our business to the buyer.</p>
    				<p>* Where we are legally required by law to disclose your personal information.</p>
    				<p>* To further fraud protection and reduce the risk of fraud.</p>
    				<div class="bottom-40"></div>
    				<h3>Third Party Links & Images</h3>
    				<p>Most of the information displayed on Compare.je is generated by third party companies. We include links & images to third parties on this website. Where we provide a link it does not mean that we endorse or approve that site's policy towards visitor privacy. You should review their privacy policy before sending them any personal data. We are also not responsible for any information or images generated by third parties.</p>
    				<div class="bottom-40"></div>
    				<h3>Jurisdiction</h3>
    				<p>This Agreement shall be governed by and construed in accordance with the Laws of Jersey, and each of the parties submits to the exclusive jurisdiction of the Courts of Jersey.</p>
    				<div class="bottom-40"></div>
    				<h3>Contacting Us</h3>
    				<p>Please do not hesitate to contact us regarding any matter relating to this Privacy and Cookies Policy via email at <a href="mailto:admin@compare.je">admin@compare.je</a></p>
    			</div>
    		</div>
    		<div class="col-md-3">
    			<img class="img-responsive bottom-10" src="assets/assest_view/images/Add.jpg" style="width:100%">
    			<img class="img-responsive bottom-10" src="assets/assest_view/images/facebook.jpg" style="width:100%">
				<iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FCompareJersey&amp;width&amp;height=590&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=true&amp;show_border=true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:590px; width:100%;" allowTransparency="true"></iframe>
				<div class="bottom-20"></div>
				<div class="row bottom-20">
					<div class="col-md-12">
						<h3 class="underline bottom-40">Contact Us</h3>
							<div class="contact-info"><span class="glyphicon glyphicon-map-marker"></span>Address</div>St Helier Jersey Channel Islands
		                	<div class="contact-info padding-top"><span class="glyphicon glyphicon-envelope"></span> E-mail</div>admin@compare.je
		                    <div class="contact-info padding-top"><span class="glyphicon glyphicon-globe"></span> Website</div>www.compare.je
		                    <div class="contact-info padding-top"><span class="glyphicon glyphicon-time"></span> Working Hours</div>9AM - 6PM , Monday - Saturday
					</div>
				</div>
			</div>
	  	</div>
	    
	@stop
@stop





